// examples/building-reactive-apps-with-rxjs-and-lit/src/app.ts
import { LitElement, css, html } from "lit";
import { customElement, state } from "lit/decorators.js";
import "./count/count-directives";
import "./count/count-lifecycle";

const components = [
  null,
  "count-lifecycle",
  "count-directive",
];

@customElement("count-app")
export class CountApp extends LitElement {
  @state() private idx = 0;

  static styles = css`
    :host {
      display: flex;
      flex-direction: column;
      gap: 1rem;
      margin: 0 auto;
      width: calc(2 / 3 * 100%);
    }

    .container {
      display: flex;
      justify-content: space-between;
      align-items: center;
    }

    button {
      padding: 0.5rem;
      font-weight: bold;
      color: currentColor;
      border: none;
      font-size: 1rem;
      background: var(--color-mariner-500);
    }

    button:hover {
      background: var(--color-mariner-700);
    }

    .container2 {
      padding: 1rem;
      background: var(--color-mariner-900);
      border: 1px solid var(--color-mariner-800);
    }
  `;

  protected render() {
    const componentName = components[this.idx];
    return html`
      <h1>RxJS + Lit</h1>
      <div class="container">
        <h2>
          Component:
          <strong>
            ${components[this.idx] ?? "No component"}
          </strong>
        </h2>
        <button
          @click=${() =>
            (this.idx = (this.idx + 1) % components.length)}
        >
          Switch
        </button>
      </div>
      ${componentName
        ? html`
            <div class="container2">
              ${document.createElement(componentName)}
            </div>
          `
        : null}
    `;
  }
}

// examples/how-to-use-rxjs-with-react/src/App.tsx
import React, { useState } from "react";
import "./App.css";
import { CountClass } from "./clock/CountClass";
import { CountCustomHook } from "./clock/CountCustomHook";
import { CountFunction } from "./clock/CountFunction";
import { CountObservableHook } from "./clock/CountObservableHook";

const components: Array<
  React.ComponentClass | React.FunctionComponent | null
> = [
  null,
  CountClass,
  CountFunction,
  CountCustomHook,
  CountObservableHook,
];

function App() {
  const [idx, setIdx] = useState(0);
  const ReactiveComponent = components[idx];
  return (
    <div className="flex flex-col gap-4 md:w-2/3 lg:w-1/2 p-4 mx-auto">
      <h1 className="text-3xl font-bold">RxJS + React</h1>
      <div className="flex justify-between items-center">
        <h2 className="text-lg">
          Component:{" "}
          <strong className="whitespace-nowrap">
            {ReactiveComponent?.name ?? "No component"}
          </strong>
        </h2>
        <button
          className="p-2 font-bold text-white bg-mariner-500 hover:bg-mariner-700"
          onClick={() =>
            setIdx((idx + 1) % components.length)
          }
        >
          Switch
        </button>
      </div>
      {ReactiveComponent && (
        <div className="p-4 bg-mariner-900 border border-mariner-800">
          <ReactiveComponent></ReactiveComponent>
        </div>
      )}
    </div>
  );
}

export default App;
